language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: bintray
  file: Path to a descriptor file, containing information for the Bintray upload
  user: lind
  passphrase: Optional. In case a passphrase is configured on Bintray and GPG signing
    is used
  dry-run: true
env:
  global:
  - secure: skustHzhx6aHqNVfp6n8YC6sznRUwwYaE3dL+2SHUHU3x+fTafP6zyY4iBCJAniWrXQ052m+KEc+Xqpe3eWwPXz5LyvjaMi9zB78UFsHTfPeDJcllnbyYeF1zJ+AshqThcYoNie9WscNU9ks9p9Nz8Y74tWZAtP+6su263KtMxGGhOT0xuzv5cJlL8yxMh1J+TE+rChHdVnbFpkwpWa0MgSp1m9gYt+r1Vo7zlbgC+lyuvDRSFTXTbLRWWG+HNLrMtBbwGy2Sm9nxFIcr6OL4hy3mEO8uPldPin1Yx8l/5/Z80nLXFLdyp/9upfc1qpty+MBKejbrjhNgr3B1lx6YEp88R0oEQKIiDf4qhbtDHv8hItpOK2CmHc7rAT+qEqUYXx0QTmxpSjwmFC35T3XHfcxJhFGGUlSYCnF3STJyxQMriPAMrBjKCDYDxQX8Is7hvF6sXJEwpuqeCUsn8e2t7tfSGaUpHYVKb2A8T/B1CWZKkX3m9JuehAszyM3IFdpSTA/ogqoMJ2/jOQ84UlxTPkIGjDdeGCCwyG1SzFsKLW0q8V8ypA7Yh/9leU23Sj1FWA0ag1o5tP1lrc7pnyFMvyWa/fkb8wdmahSKYcg7gSrLaU3AkP0E6clInqvou26SsuvIdsgtgPfWSTPOc8MioqSlix333I6kvA7CliixKo=
  - secure: DwRasampJ9RH5LE9uEtR6Y2Ea9AJdYNpeXO5OHINKFtJdSFFImElIaa/KFcNdomI6Y9Pkzck66oQRinYGBIz1nF/Ng19qgjnL3j6yu37fkwrbYiD/mck4K6HOQ9SJUNQ9hAlj+BuXRshONj5ePDKrmx8nRLnzdqXv+gJEj5f4Mw7PCdjJ195V3z8p+RnmBgoY7QJrRkolhwYMq2GQJVqSQaKg9lfKu2fnFU/of78AhauE5SdHSvfCCfR2NNm9ma18O1oLtfYOtqwiA2q/nnJdH1yrik0wQFDrudJoKe5jVnSdxIzD1Umj3TOh4XH8ZlsfefacygT7E1GpGK53hlZJc6yO7T3AEEYtLPvu10TuS0mHsHwCyiElkz9aTqLm7HyXrOKCKsQsyp/1OpfBb1GF+I0+XlmbDMTkkJj7a9PBDPGkG37jkr/Jcr92mpbZu1dXGyBsu1JJqSEiVMN7uNomm7C0x1UqHAEirmK49hFHCO+66MPwr9dQ8wN0JmSQOVaij2YZhOeiVnMbYhOAJsFB2wB8hVZ/V5O7Oo7P6RgEHeLlhpBTgOz3GR5v06sl4x7Cnw7FXCd07nJpj5XmSRIzVxJins10J1qem4WfPuyDJ9uo/slzMWsX/Aja67QId9B2B8as4v0RiT8NKdGAh8UPbUsCT/5rRnwdA4otcMG2Zs=
