language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: bintray
  dry-run: true
env:
  global:
  - secure: DwRasampJ9RH5LE9uEtR6Y2Ea9AJdYNpeXO5OHINKFtJdSFFImElIaa/KFcNdomI6Y9Pkzck66oQRinYGBIz1nF/Ng19qgjnL3j6yu37fkwrbYiD/mck4K6HOQ9SJUNQ9hAlj+BuXRshONj5ePDKrmx8nRLnzdqXv+gJEj5f4Mw7PCdjJ195V3z8p+RnmBgoY7QJrRkolhwYMq2GQJVqSQaKg9lfKu2fnFU/of78AhauE5SdHSvfCCfR2NNm9ma18O1oLtfYOtqwiA2q/nnJdH1yrik0wQFDrudJoKe5jVnSdxIzD1Umj3TOh4XH8ZlsfefacygT7E1GpGK53hlZJc6yO7T3AEEYtLPvu10TuS0mHsHwCyiElkz9aTqLm7HyXrOKCKsQsyp/1OpfBb1GF+I0+XlmbDMTkkJj7a9PBDPGkG37jkr/Jcr92mpbZu1dXGyBsu1JJqSEiVMN7uNomm7C0x1UqHAEirmK49hFHCO+66MPwr9dQ8wN0JmSQOVaij2YZhOeiVnMbYhOAJsFB2wB8hVZ/V5O7Oo7P6RgEHeLlhpBTgOz3GR5v06sl4x7Cnw7FXCd07nJpj5XmSRIzVxJins10J1qem4WfPuyDJ9uo/slzMWsX/Aja67QId9B2B8as4v0RiT8NKdGAh8UPbUsCT/5rRnwdA4otcMG2Zs=
  - secure: KyZHJZz0vBjLKF1htGdch5J23czaMNE8UqzpQwBOFbh8JlI+7psDlJkkJMhTSF89CTZQVRelKa8LJRwvgrpY9N6nJ10KFZcAL2JUmb2cunX5mb73LwCbfsAelLFdyFgWFFZyi2ZU7JIb4fgx5AfSQDOhve8tN3JGlumXo2p0Uor4VXF5fWGPZBZ3Soa3HtHlktS4cXCubSnYZYfZokha9Sk4repzV3L9+jDM4pm5SqyTMKka15stT1vKgUa9g395G4EDjLOPD3Fc2vDsMl3Ni05639QJr5MIN92Jtma3X3+fZYpgaKPian8nB7tiNTH7kYZq/9UIvvcemOsdOPrsabvyZTCagZQYgoS/myJ5OqqxV0jF0HGahK/P9z+8WtKSCHX6r8lJ8OqKzjzoPWqgRq5PGCbC3Gjcdzobt6z6Ht08tX0N0ngHFpRxyalU5Wlm/aan3MtwHC0irrDMfyI+enNodh1Y5nmX+hOdnj4VjJdz3QXx3opRJEF5Zk/e+gUXgXApwvOAyXMAkmH+trE+7Zj2Y2bxVKyMQc9QW2C1cx8r8hSW5lDZjSQAE6Qk3pwhCqqYCOTtXfuBroxsvTyMYJk3D5eQmfnw5aZJuA1RscD7bH5lxv4I9ldVHPHviu9fcc7q8rVc5YQZO4SEQNT5dLVk391Vs9tBO3GUTenY56k=
