language: java
# install: sudo apt-get install graphviz -y
sudo: required # false # faster builds
# script:
jdk:
- oraclejdk8

before_install:
#  - sudo pip install --upgrade pip
#  - pip install --user codecov

after_success:
# - codecov
- ./gradlew jacocoTestReport coveralls

#after_success:
#- bash <(curl -s https://codecov.io/bash)
# - ./gradlew test jacocoTestReport coveralls
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: K9FHRtWAOV+l/IdMvw2ZOrij+JhPGIVpWr5qxnxohUxpkz21H4Q8GUSlcuhNcXoiYV/WedyVa7oBCdQfBYDMmuXkGpVhajyOcS6d84wNJ9XDFlX6Xt6zhSwcrVUGduunyrjEHJe9UIwErJWxPzvz1m3kSZ4BhJiIiKghNKtAsFIWGGHEhRTbtKn+hJZ1/1mH4vW8jQjUhj9ujsvw89DlOfJ7UeFBUE0606iNC9YJalWU6J0xYOXXZjfw8mXyTUIqsEmFg5MbAmQuDLnrOD77YrklT0Uypp4+VtpWTQ4lLe1BV8q8a1ni7gsfHy8vA26DvU3WcYwvWDJkPd7TvFjpM5AK+zlbNy0bOAiO526wPNyKcIaUenhCZmXyKqZxBHi7N/pIWfRosWTGgfQx0O5hXcxTKn4mODvuw4C+asE3Ol3XxMhcxxfcawrLqJoEUYMmWLa0swDvEUi6ZTPo7Gx5YFz5sm8fmINEWz+ZVppyUDQj0ejuO5mLQsFYlRSGkLIfrl2XoFghDL6MbK8XlNegMZanLd6PqM3sxF8LaGKdliVhXOW7k/gj0hMzJhJYUfOJhNV7D34VbWlEmhWqLxt2jt41U+Xmvn/t5Td/Cg69ukQ/yL+LUUGAqXbQYsw5YiuPJzQ39AUHbWKDGSUzfu8YMkhLadDBL4SAdM1xDiEcIUo=
