language: java
jdk:
- oraclejdk8
after_success:
- ./gradlew jacocoTestReport coveralls
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
#deploy:
#  provider: bintray
#  file: .bintray_descriptor.yml
#  user:
#    secure: 28q26vunhiOdF2lAT0tJu3Z4D7AkMb4U/OWbiWlau5+xBQnsCSWRfuz+DJTgEgd+n5Q5lhng0o9ir+AzWPj4v9aj0nD0PQc7pnf9t5APfyOfBDmDEYU2UT3R2Ou3F5/vN+S9G1O3tNfFPUqrMBDfK72nXiCP8xJzmoTbfaChJ9/HQocnZWH7cmdCOQw2OFXjyCFKVcwgbKORh9jAffXyKWafQTCzTs/sWp9IfJULX7y0droPgRhBNDbF24K+VcS9sJFK/kYXo6s6ezywbExtKSXqiDFHUXkh+MvWUa7zA2q5Cx5IvEQvy2DiMmywaijjXNT8FoDtxGZv/FNg68gCc36jAvOhfFX+cQcMnT6b+8RunSmOjsuUMYTCN49wIqoUPXL8ZErVcTDrI5P+zDQwPov3vkgZ1c18yFk/0oOP4aL1vEhaq3FAvSJ8n5cletmQJVbQb74auw13yezAue4pO7bxYiklQmal5CeHqFlzpoLVtYJAM9Zel/eZHBVhrGsS1tvFSQLJqyhfkB5dKqlBASv+dKS4mVyh8zU0kFQ/Y46iQXdmtjl3ItWh5vwa8ZtYLc8K9YopLitZ8KVlHumyEwnPxJ8wmgYzvicwtqVTfE+2LfyNtVlyLUtWgekDtr5CGOWWdqsXdUQplr+93U1mGTew90LIURTNmPJ2FSJa1gg=
#  key:
#    secure: ksBtQtgM1hf4YYqqZTcvq1rVPEeZmORrr7bB26W2PsI+volBfBCwbA1fG7G/inKdZRj1BWTZRiaBcrSDBomVGKe0edXHPOYw5nkvMq8QolGaj7E73aB7ktA+Ji7TZVooNkIdw3uel5dinXtj7++IGyv4y+FybPyP+CNwWs/zvCSabz5Rtf4rfJsg4CrfrKnbw4841DEKPC2DhkWf0FSaEplf1LSUVkbpU2BK2Ods+Hxt9WnFSclsVPXRAdjXA1pwNM8Xh3rhaSwIgOe95IBuydFSEN8j1yNReva3EKqR3mnQ/rMF80ukSKcxiZ4TUSgDb2mo/6eQhUza7Ddl1hxJeSHanYXbgpKIBqWPayWx2lVC9N/EP++RCVeeD9wjMshkRNRnYr7pXPIJ/vQNX2jEn+X0uNONSXFCjFzsMn3gLr25m0l4Gf43719+dygLVaAvfb8cBSVjMFYrmEAJDe3r3NyywBXvYc50sMKyDJIXTDSCdES4XE3pYKJcY+O+RMeuubdzGcoh6uACGKhSjVHmh+kAyEZ80DELEV7+cdJjo7PHCliu45SdJYRNRh1SVWtGj8o9TkJ6VUkH3bmLEulKvQuJvUbLWkXkbLlVuAMN/E+K+35WsK2llkbhKVHCjwe6DbN0mVfUWwEUk55MbL20gOmdCeMjeyQCipPv+BAeY+c=
#  dry-run: true
